Name:           perl-Data-Page-Pageset
Version:        1.02
Release:        0.1%{?dist}
Summary:        Change long page list to be shorter and well navigate
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Data-Page-Pageset/
Source0:        http://www.cpan.org/authors/id/C/CH/CHUNZI/Data-Page-Pageset-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Pages number can be very high, and it is not comfortable to show user from
the first page to the last page list. Sometimes we need split the page list
into some sets to shorten the page list, the form is like:

%prep
%setup -q -n Data-Page-Pageset-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Mar 19 2016 Nico Kadel-Garcia <nkadel@gmail.com> 1.02-0.1
- Specfile autogenerated by cpanspec 1.78.
- Add Test::more to BuildRequires.
