Name:           perl-File-Dropbox
Version:        0.6
Release:        0.1%{?dist}
Summary:        Convenient and fast Dropbox API abstraction
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/File-Dropbox/
Source0:        http://www.cpan.org/authors/id/N/NF/NFOKZ/File-Dropbox-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Furl) >= 2.16
BuildRequires:  perl(IO::Socket::SSL) >= 1.4
BuildRequires:  perl(JSON) >= 2.0
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Net::DNS::Lite) >= 0.1
Requires:       perl(Furl) >= 2.16
Requires:       perl(IO::Socket::SSL) >= 1.4
Requires:       perl(JSON) >= 2.0
Requires:       perl(Net::DNS::Lite) >= 0.1
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
File::Dropbox provides high-level Dropbox API abstraction based on
Tie::Handle. Code required to get access_token and access_secret for signed
OAuth 1.0 requests or access_token for OAuth 2.0 requests is not included
in this module. To get app_key and app_secret you need to register your
application with Dropbox.

%prep
%setup -q -n File-Dropbox-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Mar 20 2016 Nico Kadel-Garcia <nkadel@gmail.com> 0.6-1
- Specfile autogenerated by cpanspec 1.78.
