Name:           perl-HTML-FormatText-WithLinks-AndTables
Version:        0.06
Release:        0.1%{?dist}
Summary:        Converts HTML to Text with tables intact
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/HTML-FormatText-WithLinks-AndTables/
Source0:        http://www.cpan.org/authors/id/D/DA/DALEEVANS/HTML-FormatText-WithLinks-AndTables-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTML::FormatText)
BuildRequires:  perl(HTML::FormatText::WithLinks)
BuildRequires:  perl(HTML::TreeBuilder)
BuildRequires:  perl(Test::More)
Requires:       perl(HTML::FormatText)
Requires:       perl(HTML::FormatText::WithLinks)
Requires:       perl(HTML::TreeBuilder)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module was inspired by HTML::FormatText::WithLinks which has proven to
be a useful `lynx -dump` work-alike. However one frustration was that no
other HTML converters I came across had the ability to deal affectively
with HTML <TABLE>s. This module can in a rudimentary sense do so. The aim
was to provide facility to take a simple HTML based email template, and to
also convert it to text with the <TABLE> structure intact for inclusion as
"multipart/alternative" content. Further, it will preserve both the
formatting specified by the <TD> tag "align" attribute, and will also
preserve multiline text inside of a <TD> element provided it is broken
using <BR/> tags.

%prep
%setup -q -n HTML-FormatText-WithLinks-AndTables-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc 10003.txt Changes d dist.ini LICENSE weirdo.txt weirdo.txt2 wtf.txt
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Mar 21 2016 Nico Kadel-Garcia <nkadel@gmail.com> 0.06-0.1
- Specfile autogenerated by cpanspec 1.78.
- Delete confusing single quote in description, it breaks .spec autoindentation
