Name:           perl-Furl
Version:        3.08
Release:        0.1%{?dist}
Summary:        Lightning-fast URL fetcher
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Furl/
Source0:        http://www.cpan.org/authors/id/T/TO/TOKUHIROM/Furl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(Class::Accessor::Lite)
BuildRequires:  perl(Compress::Raw::Zlib)
BuildRequires:  perl(Encode)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(HTTP::CookieJar)
BuildRequires:  perl(HTTP::Parser::XS) >= 0.11
BuildRequires:  perl(IO::Socket::SSL)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Mozilla::CA)
BuildRequires:  perl(Net::IDN::Encode)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Socket)
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(Test::Requires)
BuildRequires:  perl(Test::TCP) >= 2.11
BuildRequires:  perl(Time::HiRes)
Requires:       perl(Class::Accessor::Lite)
Requires:       perl(Compress::Raw::Zlib)
Requires:       perl(Encode)
Requires:       perl(HTTP::CookieJar)
Requires:       perl(HTTP::Parser::XS) >= 0.11
Requires:       perl(IO::Socket::SSL)
Requires:       perl(Mozilla::CA)
Requires:       perl(Net::IDN::Encode)
Requires:       perl(Scalar::Util)
Requires:       perl(Socket)
Requires:       perl(Time::HiRes)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Furl is yet another HTTP client library. LWP is the de facto standard HTTP
client for Perl 5, but it is too slow for some critical jobs, and too
complex for weekend hacking. Furl resolves these issues. Enjoy it!

%prep
%setup -q -n Furl-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
echo "Skipping tests, which hang forever on RHEL 7"
echo ./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json README.md TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Mar 20 2016 Nico Kadel-Garcia <nkadel@gmail.com> 3.08-0.1
- Specfile autogenerated by cpanspec 1.78.
- Cancel tests, they hang forever on RHEL 7.

